const ACTIONS_TYPE = {
    'ADD_USER':"ADD-USER",
    'DELETE_USER':"DELETE-USER",
    'UPDATE_USER':'UPDATE-USER',
    'SHOW_USER':'SHOW-USER',
    'EDIT_USER':'EDIT-USER',
    'FIND_USER':'FIND-USER',
    'GET_USER':'GET-USER',
    
}

export default ACTIONS_TYPE;